#!/usr/bin/env bash
# This script displays lists of currently running processes
# Must show all processes , for all users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierrachy

ps -a -x -u -f
